"""users and measurements tables

Revision ID: a884f181ec35
Revises: 
Create Date: 2019-05-12 10:26:02.172125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a884f181ec35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('user_measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('chest', sa.Numeric(), nullable=True),
    sa.Column('upper_chest', sa.Numeric(), nullable=True),
    sa.Column('waist', sa.Numeric(), nullable=True),
    sa.Column('hips', sa.Numeric(), nullable=True),
    sa.Column('right_thigh', sa.Numeric(), nullable=True),
    sa.Column('left_thigh', sa.Numeric(), nullable=True),
    sa.Column('right_arm', sa.Numeric(), nullable=True),
    sa.Column('left_arm', sa.Numeric(), nullable=True),
    sa.Column('belly_button', sa.Numeric(), nullable=True),
    sa.Column('stomach', sa.Numeric(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_measurement_timestamp'), 'user_measurement', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_measurement_timestamp'), table_name='user_measurement')
    op.drop_table('user_measurement')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
